services:
  postgres:
    image: postgres:16
    container_name: cycling_app_postgres
    environment:
      POSTGRES_DB: cycling_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cycling_app_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: cycling_app_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data: